name: 'Merge developement to master Action'
description: 'Action to merge the development branch to master.'
runs:
  using: "composite"
  steps:
    - name: Merge development to master
      shell: bash
      run: |
        cd source
        git fetch
        git checkout main
        git merge development
        # push merged changes to remote
        git push origin main